export const reservasMock = [
  {
    id: 1,
    date: "15",
    month: "SET",
    year: "2023",
    clientName: "Ana Silva",
    clientLocation: "Vila Madalena, SP",
    clientAvatar:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=688&q=80",
    service: "Hospedagem",
    duration: "4 noites",
    petName: "Thor",
    petBreed: "Golden Retriever",
    status: "confirmada",
    location: "Vila Madalena, São Paulo - SP",
    checkIn: "15/09/2023 às 14h",
    checkOut: "19/09/2023 às 12h",
    total: "R$ 180,00",
    message:
      "Sua solicitação de reserva foi enviada para Ana Silva. Você receberá uma confirmação em até 24 horas.",
    nextSteps: [
      { icon: null, text: "Aguarde a confirmação do anfitrião" },
      { icon: null, text: "O pagamento será processado após a confirmação" },
      { icon: null, text: "Você receberá lembretes antes do check-in" },
      { icon: null, text: "Dúvidas? Entre em contato com o suporte" },
    ],
  },
  {
    id: 2,
    date: "20",
    month: "SET",
    year: "2023",
    clientName: "Bruno Costa",
    clientLocation: "Pinheiros, SP",
    clientAvatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=688&q=80",
    service: "Passeio",
    duration: "1 hora",
    petName: "Mimi",
    petBreed: "Gato Persa",
    status: "pendente",
    location: "Pinheiros, São Paulo - SP",
    checkIn: "20/09/2023 às 10h",
    checkOut: "20/09/2023 às 11h",
    total: "R$ 50,00",
    message:
      "Sua solicitação de reserva foi enviada para Bruno Costa. Aguardando confirmação.",
    nextSteps: [
      { icon: null, text: "Aguarde a confirmação do anfitrião" },
      { icon: null, text: "O pagamento será processado após a confirmação" },
      { icon: null, text: "Você receberá lembretes antes do check-in" },
    ],
  },
  {
    id: 3,
    date: "05",
    month: "AGO",
    year: "2023",
    clientName: "Carla Fernandes",
    clientLocation: "Moema, SP",
    clientAvatar:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&auto=format&fit=crop&w=688&q=80",
    service: "Hospedagem",
    duration: "3 noites",
    petName: "Rex",
    petBreed: "Labrador",
    status: "concluida",
    location: "Moema, São Paulo - SP",
    checkIn: "05/08/2023 às 15h",
    checkOut: "08/08/2023 às 12h",
    total: "R$ 270,00",
    message: "Reserva concluída com sucesso.",
    nextSteps: [
      { icon: null, text: "Avalie o cuidador" },
      { icon: null, text: "Compartilhe sua experiência" },
    ],
  },
  {
    id: 4,
    date: "12",
    month: "JUL",
    year: "2023",
    clientName: "Daniel Oliveira",
    clientLocation: "Jardins, SP",
    clientAvatar:
      "https://images.unsplash.com/photo-1527980965255-d3b416303d12?ixlib=rb-4.0.3&auto=format&fit=crop&w=688&q=80",
    service: "Hospedagem",
    duration: "5 noites",
    petName: "Luna",
    petBreed: "Shih Tzu",
    status: "cancelada",
    location: "Jardins, São Paulo - SP",
    checkIn: "12/07/2023 às 14h",
    checkOut: "17/07/2023 às 12h",
    total: "R$ 200,00",
    message: "Reserva cancelada pelo cliente.",
    nextSteps: [{ icon: null, text: "Entre em contato com o suporte se necessário" }],
  },
];
